name: Features - Hourly

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

concurrency:
  group: features-hourly
  cancel-in-progress: true

jobs:
  build-features:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build features (append yesterday)
        env:
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
        run: |
          # Build features for the last 1 day (pipeline excludes today -> uses yesterday)
          python Data_Collection/feature_store_pipeline.py \
            --days 1 \
            --impute_short_gaps \
            --min_hours_per_day 16 \
            --append

      - name: Quick sanity check
        run: |
          python - << 'PY'
          import pandas as pd
          df = pd.read_csv('Data/feature_store/karachi_daily_features.csv')
          neg = {c:int((df[c]<0).sum()) for c in ['pm2_5_mean','pm10_mean','co_mean','no_mean','no2_mean','o3_mean','so2_mean','nh3_mean'] if c in df.columns}
          print('NEGATIVE_COUNTS:', neg)
          PY

      - name: Upload feature artifacts
        uses: actions/upload-artifact@v4
        with:
          name: features-${{ github.run_id }}
          path: |
            Data/feature_store/karachi_daily_features.parquet
            Data/feature_store/karachi_daily_features.csv
            Data/raw/karachi_air_pollution.csv
          retention-days: 10


